/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2025--, scikit-bio development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Native binary that runs each PCoACase through skbb::pcoa_fsvd and
 * writes the observed (eigenvalues, samples, proportion_explained) as a
 * C header consumed by test_pcoa_wasm.cpp.
 *
 * Unlike PERMANOVA, PCoA results are allowed to differ between
 * native-LAPACK and WASM-Eigen paths (different QR/SVD algorithms can
 * produce different rotations / sign conventions). The test uses
 * absolute-value comparison per axis and a generous tolerance; the
 * expected values captured here are the LAPACK reference.
 *
 * MUST be invoked with OMP_NUM_THREADS=1. PCoA doesn't use the RNG-
 * chunking heuristic directly, but skbb::set_random_seed(s) is the only
 * input to Halko's Gaussian matrix: if something changes upstream that
 * makes this sensitive to thread count we want a deterministic baseline.
 */

#include "ordination/principal_coordinate_analysis.hpp"
#include "util/rand.hpp"

#include "tests/wasm/pcoa_inputs.hpp"

#include <cstdio>
#include <cstdlib>
#include <string>

static void emit_double_array(const char *name, const double *buf, unsigned int n) {
    std::printf("static const double %s[] = {\n", name);
    for (unsigned int i = 0; i < n; ++i) {
        std::printf("    %a%s\n", buf[i], (i + 1 == n) ? "" : ",");
    }
    std::printf("};\n\n");
}

int main() {
    const char *nt = std::getenv("OMP_NUM_THREADS");
    if (nt == nullptr || std::string(nt) != "1") {
        std::fprintf(stderr,
            "ERROR: generate_pcoa_expected must run with "
            "OMP_NUM_THREADS=1 (got '%s').\n",
            nt ? nt : "(unset)");
        return 2;
    }

    using namespace skbb_wasm_test;

    std::printf("/* GENERATED by generate_pcoa_expected.cpp — do not edit. */\n");
    std::printf("#ifndef SKBB_WASM_PCOA_EXPECTED_H\n");
    std::printf("#define SKBB_WASM_PCOA_EXPECTED_H\n\n");
    std::printf("namespace skbb_wasm_test {\n\n");

    for (unsigned int i = 0; i < kPCoACaseCount; ++i) {
        const PCoACase &c = kPCoACases[i];
        const unsigned int n = c.n;
        const unsigned int k = c.n_eighs;

        double *eigenvalues = new double[k];
        double *samples     = new double[uint64_t(n) * k];
        double *prop        = new double[k];

        // Seed skbb's global RNG as well, for parity with the WASM path
        // even though pcoa_fsvd itself accepts a seed parameter.
        skbb::set_random_seed(static_cast<unsigned int>(c.seed));
        skbb::pcoa_fsvd(n, c.mat, k, c.seed,
                        eigenvalues, samples, prop);

        char base[128];
        std::snprintf(base, sizeof(base), "pcoa_%s", c.name);

        {
            char buf[160];
            std::snprintf(buf, sizeof(buf), "%s_eigenvalues", base);
            emit_double_array(buf, eigenvalues, k);
        }
        {
            char buf[160];
            std::snprintf(buf, sizeof(buf), "%s_samples", base);
            emit_double_array(buf, samples, uint64_t(n) * k);
        }
        {
            char buf[160];
            std::snprintf(buf, sizeof(buf), "%s_proportion_explained", base);
            emit_double_array(buf, prop, k);
        }

        delete[] eigenvalues;
        delete[] samples;
        delete[] prop;
    }

    // Emit a dispatch table so the test can look up expected arrays by index.
    std::printf("struct PCoAExpected {\n"
                "    const double *eigenvalues;\n"
                "    const double *samples;\n"
                "    const double *proportion_explained;\n"
                "};\n\n");
    std::printf("static const PCoAExpected kPCoAExpected[] = {\n");
    for (unsigned int i = 0; i < kPCoACaseCount; ++i) {
        const PCoACase &c = kPCoACases[i];
        std::printf("    { pcoa_%s_eigenvalues, pcoa_%s_samples, pcoa_%s_proportion_explained },\n",
                    c.name, c.name, c.name);
    }
    std::printf("};\n\n");

    std::printf("}  // namespace skbb_wasm_test\n\n");
    std::printf("#endif\n");
    return 0;
}
