/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2025--, scikit-bio development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Native binary that runs each PermanovaCase through skbb::permanova and
 * emits the observed (fstat, pvalue) values as a C header consumed by
 * test_permanova_wasm.cpp.
 *
 * The header is checked into the repo so the WASM test is hermetic:
 * it doesn't need skbb's native build at test time, only the precomputed
 * expected values.
 *
 * MUST be invoked with OMP_NUM_THREADS=1. The WASM build is
 * single-threaded, and pmn_get_max_parallelism() returns 32 there
 * (matching 2*1*16 on native). Any other thread count changes the RNG
 * chunking and thus the permutation sequence, breaking bit-equality.
 * The Makefile rule enforces this.
 *
 * Regenerate with:  make -C src wasm_regen_permanova_expected
 */

#include "distance/permanova.hpp"
#include "tests/wasm/permanova_inputs.hpp"

#include <cstdio>
#include <cstdlib>
#include <string>

int main() {
    // Belt-and-suspenders: abort if the operator forgot OMP_NUM_THREADS=1.
    const char *nt = std::getenv("OMP_NUM_THREADS");
    if (nt == nullptr || std::string(nt) != "1") {
        std::fprintf(stderr,
            "ERROR: generate_permanova_expected must run with "
            "OMP_NUM_THREADS=1 (got '%s').\n",
            nt ? nt : "(unset)");
        return 2;
    }

    using namespace skbb_wasm_test;

    std::printf("/* GENERATED by generate_permanova_expected.cpp — do not edit. */\n");
    std::printf("#ifndef SKBB_WASM_PERMANOVA_EXPECTED_H\n");
    std::printf("#define SKBB_WASM_PERMANOVA_EXPECTED_H\n\n");
    std::printf("namespace skbb_wasm_test {\n\n");
    std::printf("struct PermanovaExpected { double fstat; double pvalue; };\n\n");
    std::printf("static const PermanovaExpected kPermanovaExpected[] = {\n");

    for (unsigned int i = 0; i < kPermanovaCaseCount; ++i) {
        const PermanovaCase &c = kPermanovaCases[i];
        double fstat = 0.0, pvalue = 0.0;
        skbb::permanova(c.n, c.mat, c.grouping, c.n_perm, c.seed, fstat, pvalue);
        // %a emits the exact hex representation of the double, so no
        // precision is lost in the round-trip. The decimal comment is for
        // human readability when the header shows up in diffs.
        std::printf("    { %a, %a },  /* %s: fstat=%.17g pvalue=%.17g */\n",
                    fstat, pvalue, c.name, fstat, pvalue);
    }

    std::printf("};\n\n");
    std::printf("}  // namespace skbb_wasm_test\n\n");
    std::printf("#endif\n");
    return 0;
}
