/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2025--, scikit-bio development team.
 * All rights reserved.
 *
 * See LICENSE file for more details
 */

/*
 * Stage 3: PERMANOVA correctness under WASM.
 *
 * Replays the same fixed inputs (permanova_inputs.hpp) through the WASM
 * build of skbb_permanova_fp64 and compares against the native expected
 * values captured in expected/permanova_expected.h. Expected values are
 * generated by a single-threaded native build — see
 * generate_permanova_expected.cpp.
 *
 * Tolerance policy (both bit-identical):
 *   - fstat:  the unpermuted pseudo-F is a deterministic function of
 *             the distance matrix and grouping with no RNG dependence.
 *   - pvalue: skbb uses a portable Fisher-Yates (see
 *             util/portable_shuffle.hpp) built on the raw std::mt19937
 *             32-bit output. mt19937 is fully specified by the C++
 *             standard, so the permutation sequence is reproducible
 *             across libstdc++ (native gcc) and libc++ (emcc).
 *
 * Determinism check: the WASM permanova is run twice with identical
 * inputs and the results must be bit-identical — a sanity check against
 * RNG state leakage between calls.
 *
 * Exit 0 on success, nonzero on any mismatch.
 */

#include "scikit-bio-binaries/distance.h"

#include "tests/wasm/permanova_inputs.hpp"
#include "tests/wasm/expected/permanova_expected.h"

#include <cstdio>
#include <cstdlib>

int main() {
    using namespace skbb_wasm_test;

    static_assert(sizeof(kPermanovaExpected) / sizeof(kPermanovaExpected[0])
                  == kPermanovaCaseCount,
                  "expected-table length must match input-table length");

    int failures = 0;

    for (unsigned int i = 0; i < kPermanovaCaseCount; ++i) {
        const PermanovaCase     &c = kPermanovaCases[i];
        const PermanovaExpected &e = kPermanovaExpected[i];

        double fstat = 0.0, pvalue = 0.0;
        skbb_permanova_fp64(c.n, c.mat, c.grouping,
                            c.n_perm, c.seed, &fstat, &pvalue);

        // Determinism: second run with identical inputs, same seed.
        double fstat2 = 0.0, pvalue2 = 0.0;
        skbb_permanova_fp64(c.n, c.mat, c.grouping,
                            c.n_perm, c.seed, &fstat2, &pvalue2);

        const bool fstat_ok  = (fstat  == e.fstat);
        const bool pvalue_ok = (pvalue == e.pvalue);
        const bool det_ok    = (fstat == fstat2) && (pvalue == pvalue2);

        std::printf("  %-12s  fstat %s (got %.17g, want %.17g)  "
                    "pvalue %s (got %.17g, want %.17g)  "
                    "det %s\n",
                    c.name,
                    fstat_ok  ? "OK" : "FAIL", fstat,  e.fstat,
                    pvalue_ok ? "OK" : "FAIL", pvalue, e.pvalue,
                    det_ok    ? "OK" : "FAIL");

        if (!fstat_ok)  ++failures;
        if (!pvalue_ok) ++failures;
        if (!det_ok)    ++failures;
    }

    std::printf("%s: %u cases, %d failures\n",
                failures == 0 ? "PASS" : "FAIL",
                kPermanovaCaseCount, failures);
    return failures == 0 ? 0 : 1;
}
