# WebAssembly build rules for scikit-bio-binaries.
#
# Activated by the top-level `wasm` target. Produces libskbb_wasm.a, a
# single-threaded static archive intended to be linked into downstream
# emscripten projects (e.g. unifrac-binaries/duckdb-miint).
#
# Backend: Eigen header-only (fetched via scripts/fetch_eigen.sh).
# No OpenMP, no pthread, no GPU, no dlopen, no CPU-arch dispatch.
#
# Expected toolchain (activated emsdk on PATH):
#   emcc, em++, emar
#
# Invocation: this Makefile fragment is included from src/Makefile and
# must be run with src/ as the working directory. All test source paths
# (e.g. `tests/wasm/test_*.cpp`) are relative to src/, and `-I.` from
# WASM_CXXFLAGS resolves `#include "tests/wasm/..."` against src/.

WASM_REPO_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../../)
WASM_EIGEN_INC := $(WASM_REPO_ROOT)/.wasm-cache/eigen/include

# Compiler-independent target flags. The macros override the native Makefile's
# x86 dispatch (we explicitly don't want x86-v3/v4 object files under WASM
# regardless of what the host machine looks like) and select the Eigen
# backend in linalg_backend_eigen.cpp.
WASM_CXX      := em++
WASM_AR       := emar
WASM_CXXFLAGS := -std=c++17 -O3 -Wall -I. \
                 -I$(WASM_EIGEN_INC) \
                 -DSKBB_WASM=1 \
                 -DSKBB_BLAS_BACKEND_EIGEN=1 \
                 -DNOGPU=1 \
                 -fno-exceptions \
                 -Wno-unknown-pragmas

# Object list for the WASM archive. Mirrors the CPU-only subset of
# SKBB_OBJS from the native Makefile, minus GPU and x86-dispatch objects,
# plus the Eigen-backed linalg implementation.
WASM_OBJS := \
    util_rand.wasm.o \
    skbb_detect_acc.wasm.o \
    skbb_accapi_cpu.wasm.o \
    dist_permanova.wasm.o \
    permanova_cpu.wasm.o \
    ord_pcoa.wasm.o \
    ord_linalg_backend_eigen.wasm.o \
    skbb_extern_util.wasm.o \
    skbb_extern_distance.wasm.o \
    skbb_extern_ordination.wasm.o

# The CPU-variant source for permanova is generated by
# ./tools/generate_permanova_dyn.py (same as the native build).

libskbb_wasm.a: $(WASM_OBJS)
	rm -f $@
	$(WASM_AR) rcs $@ $(WASM_OBJS)

# ---- Compile rules (WASM) ----
# One .wasm.o per translation unit so outputs don't collide with native .o.

util_rand.wasm.o: util/rand.cpp util/rand.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

skbb_detect_acc.wasm.o: util/skbb_detect_acc.cpp util/skbb_detect_acc.hpp util/skbb_accapi.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

# The accapi CPU stub is generated the same way as the native build.
skbb_accapi_cpu.wasm.o: skbb_accapi_cpu.cpp util/skbb_accapi.hpp util/skbb_accapi_impl.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -DSKBB_ACC_NM=skbb_cpu -c $< -o $@

dist_permanova.wasm.o: distance/permanova.cpp distance/permanova.hpp distance/permanova_dyn.hpp util/skbb_accapi.hpp util/skbb_detect_acc.hpp util/rand.hpp util/skbb_dgb_info.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

permanova_cpu.wasm.o: permanova_cpu.cpp distance/permanova_dyn.hpp distance/permanova_dyn_impl.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -DSKBB_ACC_NM=skbb_cpu -c $< -o $@

ord_pcoa.wasm.o: ordination/principal_coordinate_analysis.cpp ordination/principal_coordinate_analysis.hpp ordination/linalg_backend.hpp util/skbb_dgb_info.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

ord_linalg_backend_eigen.wasm.o: ordination/linalg_backend_eigen.cpp ordination/linalg_backend.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

skbb_extern_util.wasm.o: extern/skbb_util.cpp extern/util.h util/rand.hpp util/skbb_detect_acc.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

skbb_extern_distance.wasm.o: extern/skbb_distance.cpp extern/distance.h distance/permanova.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

skbb_extern_ordination.wasm.o: extern/skbb_ordination.cpp extern/ordination.h ordination/principal_coordinate_analysis.hpp
	$(WASM_CXX) $(WASM_CXXFLAGS) -c $< -o $@

# ---- WASM test binaries ----
# Emscripten links a .wasm + .js pair; node runs the .js, which loads
# the sibling .wasm. NODERAWFS=0 is the default — we don't touch disk.
WASM_TEST_LDFLAGS := -sEXIT_RUNTIME=1 -sALLOW_MEMORY_GROWTH=1 \
                     -sENVIRONMENT=node -sNODERAWFS=0

# The public headers refer to themselves as "scikit-bio-binaries/util.h".
# Provide that prefix via a staged include directory.
wasm_test_include_stage:
	mkdir -p .wasm-test-include/scikit-bio-binaries
	cp extern/util.h .wasm-test-include/scikit-bio-binaries/util.h
	cp extern/distance.h .wasm-test-include/scikit-bio-binaries/distance.h
	cp extern/ordination.h .wasm-test-include/scikit-bio-binaries/ordination.h

test_smoke_wasm.js: libskbb_wasm.a tests/wasm/test_smoke.cpp wasm_test_include_stage
	$(WASM_CXX) $(WASM_CXXFLAGS) -I.wasm-test-include \
	  tests/wasm/test_smoke.cpp libskbb_wasm.a \
	  $(WASM_TEST_LDFLAGS) -o $@

test_permanova_wasm.js: libskbb_wasm.a tests/wasm/test_permanova_wasm.cpp \
                       tests/wasm/permanova_inputs.hpp \
                       tests/wasm/expected/permanova_expected.h \
                       wasm_test_include_stage
	$(WASM_CXX) $(WASM_CXXFLAGS) -I.wasm-test-include \
	  tests/wasm/test_permanova_wasm.cpp libskbb_wasm.a \
	  $(WASM_TEST_LDFLAGS) -o $@

test_center_wasm.js: libskbb_wasm.a tests/wasm/test_center_wasm.cpp \
                    wasm_test_include_stage
	$(WASM_CXX) $(WASM_CXXFLAGS) -I.wasm-test-include \
	  tests/wasm/test_center_wasm.cpp libskbb_wasm.a \
	  $(WASM_TEST_LDFLAGS) -o $@

test_pcoa_wasm.js: libskbb_wasm.a tests/wasm/test_pcoa_wasm.cpp \
                  tests/wasm/pcoa_inputs.hpp \
                  tests/wasm/expected/pcoa_expected.h \
                  wasm_test_include_stage
	$(WASM_CXX) $(WASM_CXXFLAGS) -I.wasm-test-include \
	  tests/wasm/test_pcoa_wasm.cpp libskbb_wasm.a \
	  $(WASM_TEST_LDFLAGS) -o $@

wasm_test: test_smoke_wasm.js test_permanova_wasm.js test_center_wasm.js test_pcoa_wasm.js
	@echo "--- smoke ---"
	node test_smoke_wasm.js
	@echo "--- permanova ---"
	node test_permanova_wasm.js
	@echo "--- center ---"
	node test_center_wasm.js
	@echo "--- pcoa ---"
	node test_pcoa_wasm.js

# Native helpers: regenerate tests/wasm/expected/*.h by running skbb on
# the fixed inputs and dumping the observed values as C headers.
# Requires the native build (libskbb_cpu.a + BLAS/LAPACKE for PCoA).
wasm_regen_permanova_expected: libskbb_cpu.a
	$(CXX) $(CXXFLAGS) \
	  tests/wasm/generate_permanova_expected.cpp libskbb_cpu.a \
	  $(LDFLAGS) -o generate_permanova_expected.exe
	mkdir -p tests/wasm/expected
	OMP_NUM_THREADS=1 ./generate_permanova_expected.exe > tests/wasm/expected/permanova_expected.h
	@echo "regenerated tests/wasm/expected/permanova_expected.h"

wasm_regen_pcoa_expected: libskbb_cpu.a
	$(CXX) $(CXXFLAGS) \
	  tests/wasm/generate_pcoa_expected.cpp libskbb_cpu.a \
	  $(LDFLAGS) $(BLASLIB) -o generate_pcoa_expected.exe
	mkdir -p tests/wasm/expected
	OMP_NUM_THREADS=1 ./generate_pcoa_expected.exe > tests/wasm/expected/pcoa_expected.h
	@echo "regenerated tests/wasm/expected/pcoa_expected.h"

.PHONY: wasm_regen_permanova_expected wasm_regen_pcoa_expected

wasm_clean:
	rm -f libskbb_wasm.a *.wasm.o *_wasm.js *_wasm.wasm
	rm -rf .wasm-test-include

.PHONY: wasm_clean wasm_test wasm_test_include_stage
