/* GENERATED by generate_pcoa_expected.cpp — do not edit. */
#ifndef SKBB_WASM_PCOA_EXPECTED_H
#define SKBB_WASM_PCOA_EXPECTED_H

namespace skbb_wasm_test {

static const double pcoa_uuf_6x6_k3_eigenvalues[] = {
    0x1.e40d38fb67cd4p-2,
    0x1.93f6f90043a9ap-3,
    0x1.2f0898ba4748ap-4
};

static const double pcoa_uuf_6x6_k3_samples[] = {
    -0x1.d667df064b81p-5,
    -0x1.cab7abb6569d9p-3,
    0x1.8cf8d35fc71e4p-4,
    -0x1.8a206ea0b7b36p-3,
    -0x1.776431b6ee1d4p-3,
    -0x1.33562b0c2d15ap-4,
    -0x1.92ec0c07f463dp-2,
    0x1.99818f5107113p-3,
    -0x1.d077d1d70d943p-4,
    0x1.42305edd7d5cep-2,
    0x1.f4be0b396a685p-3,
    0x1.0b15d89f23de6p-5,
    0x1.a7d07d36d3436p-2,
    -0x1.96b906504be48p-4,
    -0x1.e20f8b8e425aap-4,
    -0x1.5cde736cdbc97p-4,
    0x1.fce3182be4d05p-5,
    0x1.69ace46111fbp-3
};

static const double pcoa_uuf_6x6_k3_proportion_explained[] = {
    0x1.5bc8e2d7a0392p-1,
    0x1.223e4a645b6e3p-2,
    0x1.b373849bd8d8ep-4
};

static const double pcoa_uuf_6x6_k2_eigenvalues[] = {
    0x1.e40d38fb67cd5p-2,
    0x1.93f6f90043a9bp-3
};

static const double pcoa_uuf_6x6_k2_samples[] = {
    -0x1.d667df064b816p-5,
    -0x1.cab7abb6569ep-3,
    -0x1.8a206ea0b7b37p-3,
    -0x1.776431b6ee1d6p-3,
    -0x1.92ec0c07f464p-2,
    0x1.99818f5107116p-3,
    0x1.42305edd7d5cfp-2,
    0x1.f4be0b396a683p-3,
    0x1.a7d07d36d3436p-2,
    -0x1.96b906504be3fp-4,
    -0x1.5cde736cdbc97p-4,
    0x1.fce3182be4d21p-5
};

static const double pcoa_uuf_6x6_k2_proportion_explained[] = {
    0x1.5bc8e2d7a0393p-1,
    0x1.223e4a645b6e4p-2
};

struct PCoAExpected {
    const double *eigenvalues;
    const double *samples;
    const double *proportion_explained;
};

static const PCoAExpected kPCoAExpected[] = {
    { pcoa_uuf_6x6_k3_eigenvalues, pcoa_uuf_6x6_k3_samples, pcoa_uuf_6x6_k3_proportion_explained },
    { pcoa_uuf_6x6_k2_eigenvalues, pcoa_uuf_6x6_k2_samples, pcoa_uuf_6x6_k2_proportion_explained },
};

}  // namespace skbb_wasm_test

#endif
