/* GENERATED by generate_permanova_expected.cpp — do not edit. */
#ifndef SKBB_WASM_PERMANOVA_EXPECTED_H
#define SKBB_WASM_PERMANOVA_EXPECTED_H

namespace skbb_wasm_test {

struct PermanovaExpected { double fstat; double pvalue; };

static const PermanovaExpected kPermanovaExpected[] = {
    { 0x1.58p+2, 0x1.999999999999ap-2 },  /* smoke_4x4: fstat=5.375 pvalue=0.40000000000000002 */
    { 0x1.965dd411724ccp-1, 0x1.599999999999ap-1 },  /* uuf_6x6: fstat=0.79368460381479045 pvalue=0.67500000000000004 */
    { 0x1p+0, 0x1p+0 },  /* ties_8x8: fstat=1 pvalue=1 */
};

}  // namespace skbb_wasm_test

#endif
